[Standalone]
4kpVLMGIKeepPercent = 0 
; GI count budget (main lever) Default 100
4kpVLMBakeBrightness = 3.0
; Default 1.0
4kpVLMMinIntensityNonGI = 30
; trims fading flashers (free) Default 30

[TableOverride]
ViewCabMode = 2
ViewCabScaleX = 1.244614
ViewCabScaleY = 0.994746
ViewCabScaleZ = 0.859642
ViewCabRotation = 180.000000
ViewCabHOfs = 0.000000
ViewCabVOfs = 0.041922
ViewCabWindowTop = 382.045959
ViewCabWindowBot = 139.308258

[Player]
ScreenPlayerY = 14.982994
ScreenPlayerZ = 89.993927

[TableOption]
Desktop DMD = 0.000000
Outpost Difficulty = 2.000000
Snake Ramp Mod = 0.000000
Cemetery Mod = 0.000000
Shaker SSF = 1.000000
Shaker SSF Intensity = 2.000000
Playfield Glass = 0.000000
Playfield Reflections = 0.000000
VR Room = 2.000000
VR BL Room Srobes = 0.000000
Color Saturation = 1.000000
Mech Volume = 0.800000
Ball Roll Volume = 0.500000
Ramp Roll Volume = 0.500000