

[TableOverride]
ViewCabMode = 2
ViewCabScaleX = 1.226688
ViewCabScaleY = 1.022402
ViewCabScaleZ = 1.000000
ViewCabRotation = 180.000000
ViewCabHOfs = 0.159700
ViewCabVOfs = -14.125204
ViewCabWindowTop = 367.426910
ViewCabWindowBot = 153.684204
ToneMapper = 1

[Player]
ScreenPlayerY = 25.293413
ScreenPlayerZ = 99.345154
ScreenWidth = 0.000000
ScreenHeight = 0.000000
ScreenInclination = 0.000000
; Nudge
LRAxis                          = 1
LRAxisFlip                      = 
UDAxis                          = 2
UDAxisFlip                      = 
PBWEnabled                      = 0
AAFactor = 0.45
ForceBloomOff                   = 1
SyncMode                        = 0
MaxPrerenderedFrames            = 1
FXAA                            = 1
CacheMode = 1
MaxTexDimension = 1536
OverrideTableEmissionScale = 1
DynamicDayNight = 0
EmissionScale = 0.806385
 

[TableOption]
VR Room = 4.000000
Cooperative Mode = 1.000000