[buttonLabels]
leftFlipper = "Left Side Up"
rightFlipper = "Right Side Up"
leftNudge = "Left Side Down"
rightNudge = "Right Side Down"
;dpadUp = "Launch"
;dpadDown = "Down"
;dpadLeft = "Left"
;dpadRight = "Right"
;nudge = "Nudge"
;start = "Start"
;menu = "Menu"
