name: Check table.ini

on:
  pull_request:
    paths:
      - '**table.ini'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 50 # Adjust this value as needed

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get changed table.ini files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -w 'table\.ini$')
          echo "CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ',')" >> $GITHUB_OUTPUT
  
      - name: Check table.ini files
        run: |
          if [[ -n "${{ steps.changed-files.outputs.CHANGED_FILES }}" ]]; then
            IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.CHANGED_FILES }}"
            for file in "${FILES[@]}"; do
              echo "Checking \"$file\""
              python .github/workflows/scripts/check-table-ini.py "$file" "Default_VPinballX.ini"
            done
          else
            echo "No table.ini files were changed."
          fi